# Generated by Django 6.0.3 on 2026-03-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_watchlist_noofratings_watchlist_avg_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='NoOfRatings',
            new_name='no_of_Ratings',
        ),
    ]
